function msg = geometry_msgs_PointStruct
% Message struct definition for geometry_msgs/Point
coder.inline("never")
msg = struct(...
    'MessageType','geometry_msgs/Point',...
    'X',ros.internal.ros.messages.ros.default_type('double',1),...
    'Y',ros.internal.ros.messages.ros.default_type('double',1),...
    'Z',ros.internal.ros.messages.ros.default_type('double',1));
coder.cstructname(msg,'geometry_msgs_PointStruct_T');
if ~isempty(coder.target)
    coder.ceval('//',coder.rref(msg));
end
end
