function msg = sensor_msgs_PointCloud2Struct
% Message struct definition for sensor_msgs/PointCloud2
coder.inline("never")
msg = struct(...
    'MessageType','sensor_msgs/PointCloud2',...
    'Header',std_msgs_HeaderStruct,...
    'Height',ros.internal.ros.messages.ros.default_type('uint32',1),...
    'Width',ros.internal.ros.messages.ros.default_type('uint32',1),...
    'Fields',sensor_msgs_PointFieldStruct,...
    'IsBigendian',ros.internal.ros.messages.ros.default_type('logical',1),...
    'PointStep',ros.internal.ros.messages.ros.default_type('uint32',1),...
    'RowStep',ros.internal.ros.messages.ros.default_type('uint32',1),...
    'Data',ros.internal.ros.messages.ros.default_type('uint8',NaN),...
    'IsDense',ros.internal.ros.messages.ros.default_type('logical',1));
coder.cstructname(msg,'sensor_msgs_PointCloud2Struct_T');
coder.varsize('msg.Fields',[1000000000 1],[1 0]);
coder.varsize('msg.Data',[1000000000 1],[1 0]);
msg.Fields = msg.Fields([],1);
if ~isempty(coder.target)
    coder.ceval('//',coder.rref(msg));
end
end
