function msg = sensor_msgs_PointFieldStruct
% Message struct definition for sensor_msgs/PointField
coder.inline("never")
msg = struct(...
    'MessageType','sensor_msgs/PointField',...
    'INT8',ros.internal.ros.messages.ros.default_type('uint8',1,1),...
    'UINT8',ros.internal.ros.messages.ros.default_type('uint8',1,2),...
    'INT16',ros.internal.ros.messages.ros.default_type('uint8',1,3),...
    'UINT16',ros.internal.ros.messages.ros.default_type('uint8',1,4),...
    'INT32',ros.internal.ros.messages.ros.default_type('uint8',1,5),...
    'UINT32',ros.internal.ros.messages.ros.default_type('uint8',1,6),...
    'FLOAT32',ros.internal.ros.messages.ros.default_type('uint8',1,7),...
    'FLOAT64',ros.internal.ros.messages.ros.default_type('uint8',1,8),...
    'Name',ros.internal.ros.messages.ros.char('string',0),...
    'Offset',ros.internal.ros.messages.ros.default_type('uint32',1),...
    'Datatype',ros.internal.ros.messages.ros.default_type('uint8',1),...
    'Count',ros.internal.ros.messages.ros.default_type('uint32',1));
coder.cstructname(msg,'sensor_msgs_PointFieldStruct_T');
coder.varsize('msg.Name',[1 1000000000],[0 1]);
if ~isempty(coder.target)
    coder.ceval('//',coder.rref(msg));
end
end
